title: Kaiwu
page-top-title: Kaiwu
top-section-bg-text: KaiwuDataset
home-subtitle: Kaiwu&ensp;|&ensp; A Multimodal Manipulation Dataset and Framework for Robot Learning and Human-Robot Interaction
copyright-text: '&copy; Kaiwu, State KeyLab of Autonomous Intelligent Unmanned Systems, Tongji University Shanghai 200120.China.'
